#!/bin/bash

VERROU="valgrind --tool=verrou --trace=trace.inc"
CMD="./unitTest 1.1"



rm -rf covNearest && mkdir covNearest
$VERROU $CMD >/dev/null 2>/dev/null
mv trace_bb_* covNearest
genCovBB covNearest/trace_bb_cov.log-*
rename 's/(cover.*)-(.*)/$1-pid/' covNearest/cover*-*
rm covNearest/trace_bb_*.*-*

for i in `seq 1 3` ; do

    rm -rf covRandom && mkdir covRandom
    ${VERROU} --rounding-mode=random ${CMD} >/dev/null 2>/dev/null
    mv trace_bb_* covRandom
    genCovBB covRandom/trace_bb_cov.log-*
    rename 's/(cover.*)-(.*)/$1-pid/' covRandom/cover*-*
    rm covRandom/trace_bb_*.*-*
    diff -u covNearest covRandom || break
done

meld covNearest covRandom &
